name: PASCIUTI the marketing therapist
favicon: null
layout_spectrum: 0.31297
typography_spectrum: 0.67859
title: PASCIUTI the marketing therapist
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#00abd3'
    - '#d0edf6'
    - '#4dc1df'
    - '#89d4e9'
  brandStrength: 0.75
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
